baseURL = 'https://chrisullmann.github.io/bfd-hugo-site/'
languageCode = 'de-de'
title = 'Bürger für Dachau'
theme = 'hugo-simple-sections'
defaultContentLanguage = "de"

disableKinds = ["section", "taxonomy"]

[params]
  banner = "vorstand.jpg"
  email = "info@buerger-fuer-dachau.de"
  favicon = "favicon.ico"
  logo = "BfD_logo_small.png"

  [params.instagram]
    enabled = false
    tokenURL = ""
    url = ""

  [params.style]
    brandColor1 = "#F17629"
    brandColor2 = "#61A2DA"
    brandColor3 = "#ffffff"

[build]
  canonifyURLs = true
  [build.processing]
    [build.processing.css]
      postCSS = false
      minify = false

